export const DRIVERS_ACTIONS = {
  LOAD_DRIVERS: 'LOAD_DRIVERS',
  LOAD_DRIVERS_SUCCESS: 'LOAD_DRIVERS_SUCCESS',
  LOAD_DRIVERS_FAIL: 'LOAD_DRIVERS_FAIL',

  LOAD_DRIVER_RESULTS: 'LOAD_DRIVER_RESULTS',
  LOAD_DRIVER_RESULTS_SUCCESS: 'LOAD_DRIVER_RESULTS_SUCCESS',
  LOAD_DRIVER_RESULTS_FAIL: 'LOAD_DRIVER_RESULTS_FAIL',
} as const;
